### PR TITLE
Ensure Litex macro removed for cache to prevent hangs

### PR DESCRIPTION
**Pull request by ShvetankPrakash**

### CODE REVIEW

**Review by tcal-x — APPROVED** [review]
LGTM
(I thought we'd merged this a long time ago!)

**Review by tcal-x — CHANGES_REQUESTED** [review]
Need to add signoff; there should be instructions linked from the failed check.

**Comment by ShvetankPrakash** [comment]
> Need to add signoff; there should be instructions linked from the failed check.

Updated.

**Review by tcal-x — APPROVED** [review]
LGTM!

**Pull request merged**
