### PR TITLE
add framebuffer enable realted settings and utility functions

### PR DESCRIPTION
**Pull request by akioolin**
Hi :

In this pull request, I add some framebuffer stuff to enable framebuffer function for testing. 

1. add framebuffer enable realted settings in board_specific_workflows and common_socmk.
2. add simple framebuffer utility functions, includes draw line, draw box, draw string and fill box.
3. add spi card enable setting, but not start real trying.

for framebuffer output function enable, there some add on module could be add.
1. VGA version, please check the following URLs. 
https://raspi.tv/2014/gert-vga-666-review-and-video
https://hackaday.com/2016/02/21/5-vga-for-raspberry-pi/

2. HDMI version, buy a HDMI output ready fpga board, such like qmtech wukong board, nexsys video. 
https://reference.digilentinc.com/learn/programmable-logic/tutorials/nexys-video-hdmi-demo/start

BR, Akio

### CODE REVIEW

**Comment by tcal-x** [comment]
Hi @akioolin , thank you for the PR!    I'm really curious about it since I haven't played with video in LiteX much.  Will the frame buffer be connected to a DVI or VGA PMod (or built-in video connector on some boards)?

**Comment by tcal-x** [comment]
@akioolin , I guess my question is, since I do have a Nexys Video board, and I also have a VGA pmod, what further steps would I need to take to connect the frame buffer to the actual video out, and try out the options in the framebuffer software menu?

I also have the basys3 board, which has built-in VGA, but it is not yet supported in CFU Playground.

Thanks again, this is really cool!

**Comment by akioolin** [comment]
Hi, Tim:

Here is my experience. for my qmtech wukong board, the output is HDMI. But I also enable RPi VGA output module, a simple R-2R DAC. For VGA signal, there are five lines, which are h-sync, v-sync, r, g, b. If you want to try HDMI, please check  the nexsys video setting in litex boards, both in platform and targets. For VGA setting, you could refer to qmtech wukong board setting both in plarform and targets. 

HDMI path:
Step 1. Please check about nexsys video setting in litex-boards with pin connection in schematic.
Step 2. Please check the monitor's display parameter via EDID reader to get the exact video timing parameter. in this step, there some try and error to make sure right value of timing.
Step 3. Check the video timing setting in litex/litex/soc/cores/video.py. due to my used monitor is 1024x600@60Hz which is not in video.py, so I have to add the right timing setting in this file.
Step 4. Check the video framebuffer setting " --with-video-framebuffer " in litex_boards/target/board_setting.py. if there is no related setting, please refer to other boards. in "class BaseSoC(SoCCore):", the "__init__()" parameter lists, please add a field of "video_timing=1024x600@60Hz". the timing setting must be one of the records in video.py. 
Step 5. Follow my upload files, add into CFU playground, and use the following command "make PLATFORM=common_soc TARGET=qmtech_wukong USE_VIVADO=1 UART_SPEED=3000000 TTY=/dev/ttyUSB1 USE_VIDEO_FRAMEBUFFER=1 IGNORE_TIMING=0 prog load" to build needed images. After load bitstream / kernel image into fpga, you could get a menu with option "9: Framebuffer Debugging" in prompt. 
Step 6. Enter "9", and it is ready for some tests.

VGA path:
It is very similar to HDMI, just only two points different. 
1. Please check the VGA R-2R DAC schematic respect to FPGA PMOD pin assignment. If you want to enable a RGB666, 18bit colors, the total pins used are 6 pins for R, 6 pins for G, 6 pins for B, 1 pin for h-sync, 1 pin for v-sync, and some pins for GND. 20+ pins is used. 
2. Please check video phy setting. in litex_boards/target/boards.py. change the HDMI phy to VGA phy. 

BTW, the video core in litex had change from litevideo into video core in "litex/cores".

the last one have to check is the framebuffer memory address in add_video_framebuffer() in litex/soc/integration/soc.py. if you had some memory access vilation. please modify the framebuffer memory base to some where which make framebuffer work. here is my setting.
base = self.mem_map.get(name, 0x4F000000)

If you want some real case, please see the URLs. 
video demo 1: https://www.facebook.com/akioolin/videos/4528898813793899
video demo 2: https://www.facebook.com/akioolin/videos/4528898463793934

Real photo in cfu playground. sorry for my poor skill, but it still could be shown. 
If you still have problems, please let me know. 
 






BR, Akio

**Comment by akioolin** [comment]
> @akioolin , I guess my question is, since I do have a Nexys Video board, and I also have a VGA pmod, what further steps would I need to take to connect the frame buffer to the actual video out, and try out the options in the framebuffer software menu?
> 
> I also have the basys3 board, which has built-in VGA, but it is not yet supported in CFU Playground.
> 
> Thanks again, this is really cool!

Hi, Tim:

the board which you want to use for video framebuffer, it must built in DDR memory, the size of ddr memory must be large than 64MB above. for 1080p display, ARGB8888, the total needed memory size is 4*2MB ==> 8MB. 

So just try on nexsys video, do not spend any time on basys3. this my experience. 

BR, Akio

**Comment by tcal-x** [comment]
Hi @akioolin , thanks again for this.   I partly got it working on a Digilent Nexys Video board with HDMI.   I placed the framebuffer at 0x50000000, and was able to write colored sections to it using mem_write in the LiteX BIOS.   The drawings from the software menu were not quite right, but it is likely due to my monitor not exactly matching the 800x600 specification.

I will need to check with the Google licensing office regarding how to handle the bigfont.c file.  It's likely that bigfont.c will need to be moved under third_party/.  I see at the source website that it has been declared "public domain" and "free for any use".    We might need to copy that statement into the file, or place it in a LICENSE file in the same directory as bigfont.c.

**Comment by akioolin** [comment]
Hi, Tim:

It is very good progress. for framebuffer address setting. the board used has  DDR3
512MB 800MHz, and ddr memory address is start from 0x40000000 to 0x5FFFFFFF. 
since 0x10000000 means 256MB. the more better address is setting about 0x5F000000.
 which could provide most continuous memory space. 

If the line, font, drawn on monitor is not very clear, lost some part, or not shown all of draw area, etc. please try to disable cache in litex boards setting. I think the cache content is not all write back to  ddr memory.  I dont' know where to found out the cache synchronization functions, so I just disable cache. 

for font license,  You are right. This is my bad. Adding license statement in bigfont.c is good idea. 

for video path, camera input is the next target. 

BR, Akio

**Comment by tcal-x** [comment]
Hi @akioolin , this is the distortion I am seeing.   The diagonal lines are particularly interesting.   It is almost as if the low bits of the X or Y address were inverted.

This is the second monitor that I tried, and in both cases the display was similarly distorted.   I am using 800x600@60Hz.   I did not measure the monitor's parameters.

IMG_20210728_194938

I am going to push some updates to the branch -- adding some "public domain" text to the BigFont.c file, and doing some formatting to the C code.

**Review by tcal-x — APPROVED** [review]
LGTM

**Comment by akioolin** [comment]
Hi, Tim:

Many Thanks.

for the unclean display, the cache not flush complete is the root cause. After I enable cache function of vexriscv core, the below photo is like what you shown. 



BR, Akio

**Comment by akioolin** [comment]
Hi, Tim:

after some try and error, I found a solution to solve this problem. the new PR will show how solve.

BR, Akio

**Comment by tcal-x** [comment]
Hi @akioolin , is there any way to control how much BRAM the frame buffer uses, or is it fixed by the display size?   I'm trying to build for ULX3S with an ECP5-12F, and I'm running out of BRAMs.

**Comment by akioolin** [comment]
> Hi @akioolin , is there any way to control how much BRAM the frame buffer uses, or is it fixed by the display size? I'm trying to build for ULX3S with an ECP5-12F, and I'm running out of BRAMs.

Hi, Tim:

for this problem, I do some check about the memory layout of this board. the board has a 32MB SDRAM from this URL. https://radiona.org/ulx3s/

so there are some points have to check.

1. the memory layout in "csr.csv", which generated from litex soc building procedure.
in my qmtech wukong board, as shown below.
memory_region,vexriscv_debug,0xf00f0000,256,io
memory_region,rom,0x00000000,131072,cached
memory_region,sram,0x10000000,8192,cached
memory_region,main_ram,0x40000000,268435456,cached
memory_region,csr,0xf0000000,65536,io

the are two read/write memory region. one is sram, the other is main_ram. the sram is in FPGA inside which could be formed by BRAM. the main_ram is DDR / SDRAM, etc.

for framebuffer address, it must be assign to main_ram region. which means the address of framebuffer must be between start address and start address + memory size.

2. the size of ulx3s's sdram is 32MB, which is not match the statement in litex-boards/target/radiona_ulx3s.py
        # SDR SDRAM --------------------------------------------------------------------------------
        if not self.integrated_main_ram_size:
            sdrphy_cls = HalfRateGENSDRPHY if sdram_rate == "1:2" else GENSDRPHY
            self.submodules.sdrphy = sdrphy_cls(platform.request("sdram"), sys_clk_freq)
            self.add_sdram("sdram",
                phy              = self.sdrphy,
                module           = getattr(litedram_modules, sdram_module_cls)(sys_clk_freq, sdram_rate),
                size             = 0x40000000,   <==== check here.
                l2_cache_size    = kwargs.get("l2_size", 8192),
                l2_cache_reverse = False
            )

if the main_ram is not appear in csr.csv file, please check the "self.integrated_main_ram_size" attribute setting.

3. the framebuffer address setting in soc.py. should the same as #1.

4. for framebuffer size calculation as shown below
total_size = framebuffer_width * framebuffer_height * depth_of_one_pixel;

if chose 640x480@60Hz, 32bpp, the total framebuffer size is 
640*480*32/8 => 1,228,800 bytes. 

if the framebuffer base address is assigned to 0x50000000, and then
from 0x50000000 to 0x5012BFFF will be the framebuffer region.

5. in ulx3s schematic file, https://github.com/emard/ulx3s/blob/master/doc/schematics_v317.pdf, P8, the sdram is used "MT48LC16M16A2TG".
since I don't know the board's version, so I suggest check the board's version to find out which SDRAM had been used.

hope the above description could let you find out root cause.

BR, Akio

**Comment by tcal-x** [comment]
Hi @akioolin , thank you for the reply.   I did not state my issue very clearly earlier.   The problem is that when the framebuffer is enabled, the design requires a fairly large amount of block RAM on the FPGA itself, perhaps for the DMA FIFO.   On the ECP5 12F part that I have (the smallest of the family), there is not enough block RAM, even if I shrink the VexRiscv caches to zero.   The design with framebuffer will probably fit on an 85F part, but I have not been able to acquire a UXL3S board with that part.

**Comment by akioolin** [comment]
Hi, Tim:

from litex_boards/litex_boards/targets/radiona_ulx3s.py, the default SDRAM setting is been assigned to MT48LC16M16, does the SDRAM chip is MT48LC16M16 or not?

parser.add_argument("--sdram-module",    default="MT48LC16M16", help="SDRAM module: MT48LC16M16 (default), AS4C32M16 or AS4C16M16")

please do some check about the real sdram chip what is.

BR, Akio

**Pull request merged**
