### PR TITLE
Remove all instances of the payload_response_ok signal

### PR DESCRIPTION
**Pull request by GuzTech**
Since https://github.com/enjoy-digital/litex/pull/1039 was merged, remove all mentions and instances of this signal from the documentation and source code.

### CODE REVIEW

**Comment by GuzTech** [comment]
@googlebot I signed it!

**Comment by tcal-x** [comment]
Hi @GuzTech , thanks!   I've enabled tests to run for this PR.

I expect tests will fail, since we don't see the upstream LiteX changes until we bump the submodule references (and there's some other stuff that also needs to get done at the same time).   When the other stuff is in place, we will rerun tests on this PR and they should pass.

**Comment by tcal-x** [comment]
Hi @GuzTech , the upstream updates are now on the main branch here.  Can you rebase your branch on main, or merge main into your branch, so that the updates are on your fork:branch?

**Comment by tcal-x** [comment]
@GuzTech  please take a look.

**Comment by GuzTech** [comment]
@tcal-x Sorry about the late response (I have a paper deadline).

I had to fiddle around with updating my main branch and rebasing my work on top of it, but got it working in the end.

**Review by tcal-x — APPROVED** [review]
LGTM

**Comment by tcal-x** [comment]
Hi @GuzTech , thanks for this!   The failing tests show that there's one more to get -- it was probably introduced since your initial submission.   Can you remove this line too:   https://github.com/google/CFU-Playground/blob/main/common/renode-verilator-integration/sim_main.cpp#L47

**Review by tcal-x — CHANGES_REQUESTED** [review]
One more line to remove in `common/renode-verilator-integration/sim_main.cpp`.

**Comment by GuzTech** [comment]
Ah yes, that line was not present when I initially submitted my patch I think. Removed it just now.

**Comment by tcal-x** [comment]
@GuzTech Thanks for the update.   

In the CI tests, a single test timed out.  I reran, then a different test timed out.   I'll try rerunning tonight when the load is lighter.

**Review by tcal-x — APPROVED** [review]

**Pull request merged**
