### PR TITLE
Conda: constrain sysroot_linux-64>=2.17.

### LINKED ISSUE #568: Verilator compile in Conda env can't find the compiler
To reproduce: go to this colab: https://colab.research.google.com/drive/1_GlX-pO4rune8GMIK4q_IuhxpIhnPTni?resourcekey=0-jMbF8wzg0csZu0fxpOy78A&usp=sharing (currently only readable within Google)

Then select "Runtime" --> "Run all"

Output:
```
make -j -C /content/CFU-Playground/soc/build/sim.proj_template_v/gateware/obj_dir -f Vsim.mk Vsim
make[3]: Entering directory '/content/CFU-Playground/soc/build/sim.proj_template_v/gateware'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Vsim.mk:13: warning: NUL character seen; rest of line ignored
ccache x86_64-conda-linux-gnu-c++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /content/CFU-Playground/env/conda/envs/cfu-common/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /content/CFU-Playground/env/conda/envs/cfu-common/include -I.  -MMD -I/content/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include -I/content/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -DVM_TRACE_FST=1 -faligned-new -fcf-protection=none -Wno-bool-operation -Wno-sign-compare -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /content/CFU-Playground/env/conda/envs/cfu-common/include -ggdb -Wall -O0   -DTRACE_FST -I/content/CFU-Playground/third_party/python/litex/litex/build/sim/core  -std=gnu++14 -Os -c -o veril.o /content/CFU-Playground/third_party/python/litex/litex/build/sim/core/veril.cpp
ccache: error: Could not find compiler "x86_64-conda-linux-gnu-c++" in PATH
Vsim.mk:71: recipe for target 'veril.o' failed
make[3]: *** [veril.o] Error 1
make[3]: Leaving directory '/content/CFU-Playground/soc/build/sim.proj_template_v/gateware/obj_dir'
/content/CFU-Playground/third_party/python/litex/litex/build/sim/core/Makefile:38: recipe for target 'sim' failed
make[2]: *** [sim] Error 2
make[2]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/content/CFU-Playground/soc/build/sim.proj_template_v/gateware/modules/gmii_ethernet'
cp gmii_ethernet/gmii_ethernet.so gmii_ethernet.so
make[3]: Leaving directory '/content/CFU-Playground/soc/build/sim.proj_template_v/gateware/modules'
make[2]: Leaving directory '/content/CFU-Playground/soc/build/sim.proj_template_v/gateware'
/content/CFU-Playground/soc/sim.mk:56: recipe for target 'run' failed
make[1]: *** [run] Error 1
make[1]: Leaving directory '/content/CFU-Playground/soc'
../proj.mk:354: recipe for target 'load' failed
make: *** [load] Error 2
```

To highlight the error:
```
ccache: error: Could not find compiler "x86_64-conda-linux-gnu-c++" in PATH
```

Looking under `env/conda/envs/cfu-common/bin/`, I see:
```
/content/CFU-Playground/env/conda/bin/x86_64-conda-linux-gnu-ld
/content/CFU-Playground/env/conda/bin/x86_64-conda_cos6-linux-gnu-ld
```
and nothing else with an `x86_64` prefix.

### LINKED ISSUE #629: "make renode" is broken when using conda env
To reproduce:
```
make env
make enter
cd proj/proj_template_v
make renode
```
What I see:
```
make[5]: Entering directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/renode'
[  8%] Building CXX object CMakeFiles/libVtop.dir/sim_main.cpp.o
[ 16%] Building CXX object CMakeFiles/libVtop.dir/media/tim/GIT/tcal-x/CFU-Playground/third_party/renode/verilator-integration-library/src/buses/cfu.cpp.o
[ 25%] Building CXX object CMakeFiles/libVtop.dir/media/tim/GIT/tcal-x/CFU-Playground/third_party/renode/verilator-integration-library/src/renode_cfu.cpp.o
[ 33%] Building CXX object CMakeFiles/libVtop.dir/CMakeFiles/libVtop.dir/Vcfu.dir/Vcfu.cpp.o
[ 41%] Building CXX object CMakeFiles/libVtop.dir/CMakeFiles/libVtop.dir/Vcfu.dir/Vcfu___024root__DepSet_h1d3cd730__0.cpp.o
[ 50%] Building CXX object CMakeFiles/libVtop.dir/CMakeFiles/libVtop.dir/Vcfu.dir/Vcfu___024root__Slow.cpp.o
[ 58%] Building CXX object CMakeFiles/libVtop.dir/CMakeFiles/libVtop.dir/Vcfu.dir/Vcfu___024root__DepSet_h1d3cd730__0__Slow.cpp.o
[ 66%] Building CXX object CMakeFiles/libVtop.dir/CMakeFiles/libVtop.dir/Vcfu.dir/Vcfu__Syms.cpp.o
[ 75%] Building CXX object CMakeFiles/libVtop.dir/media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include/verilated.cpp.o
In file included from /media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/x86_64-conda-linux-gnu/include/c++/11.2.0/chrono:42,
                 from /media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/x86_64-conda-linux-gnu/include/c++/11.2.0/condition_variable:38,
                 from /media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include/verilated_trace.h:31,
                 from /media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include/verilated.cpp:75:
/media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/x86_64-conda-linux-gnu/include/c++/11.2.0/ctime:80:11: error: 'timespec_get' has not been declared in '::'
   80 |   using ::timespec_get;
      |           ^~~~~~~~~~~~
make[5]: *** [CMakeFiles/libVtop.dir/build.make:213: CMakeFiles/libVtop.dir/media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/share/verilator/include/verilated.cpp.o] Error 1
make[5]: Leaving directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/renode'
make[4]: *** [CMakeFiles/Makefile2:83: CMakeFiles/libVtop.dir/all] Error 2
make[4]: Leaving directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/renode'
make[3]: *** [CMakeFiles/Makefile2:90: CMakeFiles/libVtop.dir/rule] Error 2
make[3]: Leaving directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/renode'
make[2]: *** [Makefile:124: libVtop] Error 2
make[2]: Leaving directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/renode'
make[1]: *** [../proj.mk:211: renode-scripts] Error 2
make[1]: Leaving directory '/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v'
```
Potentially interrelated to #568, since this is also in the Verilator x86 compilation step.

### PR DESCRIPTION
**Pull request by tcal-x**
Tested with Ubuntu 20.04 and 18.04.

Fixes #568 and fixes #629.

Edit: For background, see my comment here: https://github.com/google/CFU-Playground/issues/568#issuecomment-1199591603 

Signed-off-by: Tim Callahan <tcal@google.com>

### CODE REVIEW

**Review by mithro — CHANGES_REQUESTED** [review]
This is not something that should be in the environment.

We should track down whatever package needs this dependency and make sure it has it as a requirement.

**Comment by tcal-x** [comment]
> This is not something that should be in the environment.
> 
> We should track down whatever package needs this dependency and make sure it has it as a requirement.

@ajelinski  did you have a theory about which packages have the 2.17 requirement?

**Comment by ajelinski** [comment]
> This is not something that should be in the environment.
> 
> We should track down whatever package needs this dependency and make sure it has it as a requirement.

Basically, Conda itself currently requires glibc >= 2.17 and by design always the host OS's glibc is used. You need to have an ancient OS to have a glibc older than that since v2.17 was released almost ten years ago. The `sysroot_linux-64` package contains glibc but it's only meant to be used by the Conda compiler when building so that the built executables won't require glibc newer than v2.17.

The constraint, however, helped @tcal-x with glibc problems which were very unusual. A glibc v2.12 from the old Conda `sysroot_linux-64` package was "mistakenly" used when running executables. There would be no issues if everything worked as designed -- using the host OS's `glibc`. This cannot happen for any new user because currently this old v2.12 package isn't even available: https://anaconda.org/main/sysroot_linux-64/files

This change can help others with the same issue and there's no better way to do it. I think the only viable alternative is leaving the environment as it is and advising such an update manually if anyone else ever reports such an issue.

> @ajelinski did you have a theory about which packages have the 2.17 requirement?

Even Python from Conda requires it -- all the packages with dynamically linked executables built for the passed 1.5 years do.

**Comment by tcal-x** [comment]
Since we have not seen the remaining issue anywhere except my laptop, I'm going to assume it is something specific to its mucked up Ubuntu installation.    It did start at 18.04, then got "upgraded" to 19.xx (which had continuous issues) when I left my previous employer, and then I upgraded again to 20.04.   I guess that explains why it has kernel 5.4, which was used with 18.04.

So, I'm going to close this.   Thanks @ajelinski for the previous fix to the Verilator package (https://github.com/hdl/conda-eda/pull/225), which I think is the real fix we needed.

**Pull request closed without merging**
