### PR TITLE
Integration of Embench IoT workloads into CFU-Playground

### PR DESCRIPTION
**Pull request by ShvetankPrakash**
These changes make it so that users can run and measure [Embench](https://github.com/embench/embench-iot) workloads in CFU-Playground. Currently we have added primecount and minver benchmarks from the Embench IoT repo. A follow up PR will add the rest (not included here to limit size of PR). 

Sample output running on icebreaker:
```
Hello, World!

CFU Playground
==============
 1: TfLM Models menu 
 2: Functional CFU Tests
 3: Project menu
 4: Performance Coter Tests
 5: TFLite Unit Tests
 6: Benchmarks
 7: Util Tests
 8: Embench IoT
 9: SPI Flash Debugging
 I: Illegal Instruction Tests (these *LL* hang on Fomu!)
main> 8

Running Embench IoT

Embench IoT
===========
 1: Primecount
 2: Minver
 x: eXit to previous menu
benchmarks> 2

Running Minver
OK  Benchmark result verified
Spent 76546207 cycles
---

Embench IoT
===========
 1: Primecount
 2: Minver
 x: eXit to previous menu
benchmarks> 1

Running Primecount
OK  Benchmark result verified
Spent 5773842 cycles
---
```

### CODE REVIEW

**Comment by mithro** [comment]
FYI - @mgielda / @pgielda / @kgugala

**Comment by tcal-x** [comment]
@ShvetankPrakash have you tried building with `export SKIP_TFLM=1` ?

**Comment by ShvetankPrakash** [comment]
> @ShvetankPrakash have you tried building with `export SKIP_TFLM=1` ?

Building the `skip_tflm` project works fine and as expected (since there is no INCLUDE_EMBENCH* in the skip_tflm makefile there is no_menu but it builds successfully":
```
CFU Playground
==============
 2: Functional CFU Tests
 3: Project menu
 4: Performance Counter Tests
 6: Benchmarks
 7: Util Tests
 8: Embench IoT
 9: SPI Flash Debugging
 I: Illegal Instruction Tes (these *WILL* hang on Fomu!)
main> 8

Running Embench IoT

Embench IoT
===========
 !: No Embench workloads selected! Check defines in Makefile!
 x: eXit  previous menu
```

Building the `embench proj` with `export SKIP_TFLM=1` added to its makefile also builds and runs as expected (i.e. builds and runs successfully with no TFLM models appearing in the menu):
```
CFU Playground
==============
 2: Functional CFU Tests
 3: Project menu
 4: Performance Counter Tests
 6: Benchmarks
 7: Util Tests
 8: Embench IoT
 9: SPI Flash Debging
 I: Illegal Instruction Tests (these *WILL* hang on Fomu
main> 8

Running Embench IoT

Embench IoT
===========
 1: Primecount
 x: eXit to previous menu
benchmarks> 1

Running Primecount
OK  Benchmark result verified
Spent 5773842 cycles
---
```

**Review by tcal-x — APPROVED** [review]
LGTM

**Pull request merged**
