### PR TITLE
Bump TFLite Micro

### PR DESCRIPTION
**Pull request by robertszczepanski**
This PR bumps TF Lite Micro and removes it form submodules. It has been generated with `create_tflm_tree.py` provided by TFLite Micro which is mentioned in #233.
This PR will be followed by a PR that adds sync CI which will automatically update `third_party/tflite-micro` nightly via PRs like in https://github.com/tensorflow/tflite-micro-arduino-examples. That PR will also add a way to update `tflite-micro` via `scripts/setup`. It is almost ready.

@tcal-x I have a question about `proj/mnv2_first/src/tensorflow/lite/kernels/internal/reference/sub.h`. How to properly update this file? Is it different than https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/kernels/internal/reference/sub.h?
Right now I just modified it manually so it seems to work with CFU Playground's demos but I don't think that's the expected solution.

### CODE REVIEW

**Comment by tcal-x** [comment]
Hi @robertszczepanski , thanks for this PR.   

As for sub.h, can you reformat both of the `sub.h` files and diff them to see what actual changes there are?

@alanvgreen, do you have any comment on why we have a custom `sub.h`?

**Comment by robertszczepanski** [comment]
I compared [sub.h](https://github.com/google/CFU-Playground/blob/main/proj/mnv2_first/src/tensorflow/lite/kernels/internal/reference/sub.h) from this repo and [sub.h](https://github.com/tensorflow/tensorflow/blob/2a96849f478627ad03b8f20f8c71e85d6d7480e3/tensorflow/lite/kernels/internal/reference/sub.h) from TF Lite which seem to be uploaded moreless in the same time (CFU Playground is from June 17, TF Lite is from June 16).
It seems that most of the changes are types (`XintY` to `XintY_t`) and CFU version has additional header included. Regardless there are more changes in `SetActivationMinMax()` and `BroadcastSubSlow()`.

<details>
<summary>Here's an output of my comparison.</summary>

```diff
diff --git a/sub_tflite.h b/sub_cfup.h
index 099808f..3df1e83 100644
--- a/sub_tflite.h
+++ b/sub_cfup.h
@@ -25,6 +25,8 @@ limitations under the License.
 #include "tensorflow/lite/kernels/internal/compatibility.h"
 #include "tensorflow/lite/kernels/internal/types.h"
 
+#include "playground_util/print_params.h"
+
 namespace tflite
 {
 
@@ -51,11 +53,11 @@ namespace tflite
 
         inline void SubNonBroadcast(const ArithmeticParams &params,
                                     const RuntimeShape &input1_shape,
-                                    const int32 *input1_data,
+                                    const int32_t *input1_data,
                                     const RuntimeShape &input2_shape,
-                                    const int32 *input2_data,
+                                    const int32_t *input2_data,
                                     const RuntimeShape &output_shape,
-                                    int32 *output_data)
+                                    int32_t *output_data)
         {
             const int flat_size =
                 MatchingElementsSize(input1_shape, input2_shape, output_shape);
@@ -120,13 +122,13 @@ namespace tflite
         template <int N = 5>
         inline void BroadcastSubSlow(const ArithmeticParams &params,
                                      const RuntimeShape &input1_shape,
-                                     const uint8 *input1_data,
+                                     const uint8_t *input1_data,
                                      const RuntimeShape &input2_shape,
-                                     const uint8 *input2_data,
+                                     const uint8_t *input2_data,
                                      const RuntimeShape &output_shape,
-                                     uint8 *output_data)
+                                     uint8_t *output_data)
         {
-            ruy::profiler::ScopeLabel label("BroadcastSubSlow/uint8");
+            ruy::profiler::ScopeLabel label("BroadcastSubSlow/uint8_t");
             TFLITE_DCHECK_LE(input1_shape.DimensionsCount(), N);
             TFLITE_DCHECK_LE(input2_shape.DimensionsCount(), N);
             TFLITE_DCHECK_LE(output_shape.DimensionsCount(), N);
@@ -150,28 +152,28 @@ namespace tflite
             // best cache behavior.
             auto sub_func = [&](int indexes[N])
             {
-                const int32 input1_val =
+                const int32_t input1_val =
                     params.input1_offset + input1_data[SubscriptToIndex(desc1, indexes)];
-                const int32 input2_val =
+                const int32_t input2_val =
                     params.input2_offset + input2_data[SubscriptToIndex(desc2, indexes)];
-                const int32 shifted_input1_val = input1_val * (1 << params.left_shift);
-                const int32 shifted_input2_val = input2_val * (1 << params.left_shift);
-                const int32 scaled_input1_val =
+                const int32_t shifted_input1_val = input1_val * (1 << params.left_shift);
+                const int32_t shifted_input2_val = input2_val * (1 << params.left_shift);
+                const int32_t scaled_input1_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input1_val, params.input1_multiplier, params.input1_shift);
-                const int32 scaled_input2_val =
+                const int32_t scaled_input2_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input2_val, params.input2_multiplier, params.input2_shift);
-                const int32 raw_sub = scaled_input1_val - scaled_input2_val;
-                const int32 raw_output =
+                const int32_t raw_sub = scaled_input1_val - scaled_input2_val;
+                const int32_t raw_output =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         raw_sub, params.output_multiplier, params.output_shift) +
                     params.output_offset;
-                const int32 clamped_output =
+                const int32_t clamped_output =
                     std::min(params.quantized_activation_max,
                              std::max(params.quantized_activation_min, raw_output));
                 output_data[SubscriptToIndex(output_desc, indexes)] =
-                    static_cast<uint8>(clamped_output);
+                    static_cast<uint8_t>(clamped_output);
             };
             NDOpsHelper<N>(output_desc, sub_func);
         }
@@ -179,13 +181,13 @@ namespace tflite
         template <int N = 5>
         inline void BroadcastSubSlow(const ArithmeticParams &params,
                                      const RuntimeShape &input1_shape,
-                                     const int32 *input1_data,
+                                     const int32_t *input1_data,
                                      const RuntimeShape &input2_shape,
-                                     const int32 *input2_data,
+                                     const int32_t *input2_data,
                                      const RuntimeShape &output_shape,
-                                     int32 *output_data)
+                                     int32_t *output_data)
         {
-            ruy::profiler::ScopeLabel label("BroadcastSubSlow/int32");
+            ruy::profiler::ScopeLabel label("BroadcastSubSlow/int32_t");
             TFLITE_DCHECK_LE(input1_shape.DimensionsCount(), N);
             TFLITE_DCHECK_LE(input2_shape.DimensionsCount(), N);
             TFLITE_DCHECK_LE(output_shape.DimensionsCount(), N);
@@ -227,7 +229,10 @@ namespace tflite
                                      const RuntimeShape &output_shape,
                                      int8_t *output_data)
         {
-            ruy::profiler::ScopeLabel label("BroadcastSubSlow/int8");
+#ifdef SHOW_ARITHMETIC_PARAMS
+            print_arithmetic_params("SUB", params, input1_shape, input2_shape, output_shape);
+#endif
+            ruy::profiler::ScopeLabel label("BroadcastSubSlow/int8_t");
             NdArrayDesc<N> desc1;
             NdArrayDesc<N> desc2;
             NdArrayDesc<N> output_desc;
@@ -274,6 +279,47 @@ namespace tflite
             NDOpsHelper<N>(output_desc, sub_func);
         }
 
+        template <int N = 5>
+        void BroadcastSubSlow(const ArithmeticParams &params,
+                              const RuntimeShape &input1_shape,
+                              const int64_t *input1_data,
+                              const RuntimeShape &input2_shape,
+                              const int64_t *input2_data,
+                              const RuntimeShape &output_shape, int64_t *output_data)
+        {
+            ruy::profiler::ScopeLabel label("BroadcastSubSlow/int64_t");
+            TFLITE_DCHECK_LE(input1_shape.DimensionsCount(), N);
+            TFLITE_DCHECK_LE(input2_shape.DimensionsCount(), N);
+            TFLITE_DCHECK_LE(output_shape.DimensionsCount(), N);
+            NdArrayDesc<N> desc1;
+            NdArrayDesc<N> desc2;
+            NdArrayDesc<N> output_desc;
+            NdArrayDescsForElementwiseBroadcast(input1_shape, input2_shape, &desc1,
+                                                &desc2);
+            CopyDimsToDesc(RuntimeShape::ExtendedShape(N, output_shape), &output_desc);
+
+            // In Tensorflow, the dimensions are canonically named (batch_number, row,
+            // col, channel), with extents (batches, height, width, depth), with the
+            // trailing dimension changing most rapidly (channels has the smallest stride,
+            // typically 1 element).
+            //
+            // In generated C code, we store arrays with the dimensions reversed. The
+            // first dimension has smallest stride.
+            //
+            // We name our variables by their Tensorflow convention, but generate C code
+            // nesting loops such that the innermost loop has the smallest stride for the
+            // best cache behavior.
+            auto sub_func = [&](int indexes[N])
+            {
+                output_data[SubscriptToIndex(output_desc, indexes)] =
+                    ActivationFunctionWithMinMax(
+                        input1_data[SubscriptToIndex(desc1, indexes)] -
+                            input2_data[SubscriptToIndex(desc2, indexes)],
+                        params.int64_activation_min, params.int64_activation_max);
+            };
+            NDOpsHelper<N>(output_desc, sub_func);
+        }
+
         template <typename T, int N = 5>
         void BroadcastSubSlow(const ArithmeticParams &params,
                               const RuntimeShape &input1_shape, const T *input1_data,
@@ -316,8 +362,8 @@ namespace tflite
         // Element-wise Sub that can often be used for inner loop of broadcast sub as
         // well as the non-broadcast sub.
         inline void SubElementwise(int size, const ArithmeticParams &params,
-                                   const uint8 *input1_data, const uint8 *input2_data,
-                                   uint8 *output_data)
+                                   const uint8_t *input1_data,
+                                   const uint8_t *input2_data, uint8_t *output_data)
         {
             TFLITE_DCHECK_GT(params.input1_offset, -256);
             TFLITE_DCHECK_GT(params.input2_offset, -256);
@@ -326,25 +372,25 @@ namespace tflite
 
             for (int i = 0; i < size; ++i)
             {
-                const int32 input1_val = params.input1_offset + input1_data[i];
-                const int32 input2_val = params.input2_offset + input2_data[i];
-                const int32 shifted_input1_val = input1_val * (1 << params.left_shift);
-                const int32 shifted_input2_val = input2_val * (1 << params.left_shift);
-                const int32 scaled_input1_val =
+                const int32_t input1_val = params.input1_offset + input1_data[i];
+                const int32_t input2_val = params.input2_offset + input2_data[i];
+                const int32_t shifted_input1_val = input1_val * (1 << params.left_shift);
+                const int32_t shifted_input2_val = input2_val * (1 << params.left_shift);
+                const int32_t scaled_input1_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input1_val, params.input1_multiplier, params.input1_shift);
-                const int32 scaled_input2_val =
+                const int32_t scaled_input2_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input2_val, params.input2_multiplier, params.input2_shift);
-                const int32 raw_sub = scaled_input1_val - scaled_input2_val;
-                const int32 raw_output =
+                const int32_t raw_sub = scaled_input1_val - scaled_input2_val;
+                const int32_t raw_output =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         raw_sub, params.output_multiplier, params.output_shift) +
                     params.output_offset;
-                const int32 clamped_output =
+                const int32_t clamped_output =
                     std::min(params.quantized_activation_max,
                              std::max(params.quantized_activation_min, raw_output));
-                output_data[i] = static_cast<uint8>(clamped_output);
+                output_data[i] = static_cast<uint8_t>(clamped_output);
             }
         }
 
@@ -362,22 +408,22 @@ namespace tflite
 
             for (int i = 0; i < size; ++i)
             {
-                const int32 input1_val = params.input1_offset + input1_data[i];
-                const int32 input2_val = params.input2_offset + input2_data[i];
-                const int32 shifted_input1_val = input1_val * (1 << params.left_shift);
-                const int32 shifted_input2_val = input2_val * (1 << params.left_shift);
-                const int32 scaled_input1_val =
+                const int32_t input1_val = params.input1_offset + input1_data[i];
+                const int32_t input2_val = params.input2_offset + input2_data[i];
+                const int32_t shifted_input1_val = input1_val * (1 << params.left_shift);
+                const int32_t shifted_input2_val = input2_val * (1 << params.left_shift);
+                const int32_t scaled_input1_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input1_val, params.input1_multiplier, params.input1_shift);
-                const int32 scaled_input2_val =
+                const int32_t scaled_input2_val =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         shifted_input2_val, params.input2_multiplier, params.input2_shift);
-                const int32 raw_sub = scaled_input1_val - scaled_input2_val;
-                const int32 raw_output =
+                const int32_t raw_sub = scaled_input1_val - scaled_input2_val;
+                const int32_t raw_output =
                     MultiplyByQuantizedMultiplierSmallerThanOneExp(
                         raw_sub, params.output_multiplier, params.output_shift) +
                     params.output_offset;
-                const int32 clamped_output =
+                const int32_t clamped_output =
                     std::min(params.quantized_activation_max,
                              std::max(params.quantized_activation_min, raw_output));
                 output_data[i] = static_cast<int8_t>(clamped_output);
@@ -385,9 +431,9 @@ namespace tflite
         }
 
         inline void Sub(const ArithmeticParams &params,
-                        const RuntimeShape &input1_shape, const uint8 *input1_data,
-                        const RuntimeShape &input2_shape, const uint8 *input2_data,
-                        const RuntimeShape &output_shape, uint8 *output_data)
+                        const RuntimeShape &input1_shape, const uint8_t *input1_data,
+                        const RuntimeShape &input2_shape, const uint8_t *input2_data,
+                        const RuntimeShape &output_shape, uint8_t *output_data)
         {
             TFLITE_DCHECK_LE(params.quantized_activation_min,
                              params.quantized_activation_max);
@@ -461,40 +507,45 @@ namespace tflite
             }
         }
 
-        inline void SubWithActivation(const ArithmeticParams &params,
-                                      const RuntimeShape &input1_shape,
-                                      const int32 *input1_data,
-                                      const RuntimeShape &input2_shape,
-                                      const int32 *input2_data,
-                                      const RuntimeShape &output_shape,
-                                      int32 *output_data)
+        inline void SetActivationMinMax(const ArithmeticParams &params,
+                                        int32_t *activation_min,
+                                        int32_t *activation_max)
         {
-            ruy::profiler::ScopeLabel label("SubWithActivation");
-            const int flat_size =
-                MatchingElementsSize(input1_shape, input2_shape, output_shape);
-            for (int i = 0; i < flat_size; ++i)
-            {
-                output_data[i] = ActivationFunctionWithMinMax(
-                    input1_data[i] - input2_data[i], params.quantized_activation_min,
-                    params.quantized_activation_max);
-            }
+            *activation_min = params.quantized_activation_min;
+            *activation_max = params.quantized_activation_max;
         }
 
-        inline void SubWithActivation(const ArithmeticParams &params,
-                                      const RuntimeShape &input1_shape,
-                                      const float *input1_data,
-                                      const RuntimeShape &input2_shape,
-                                      const float *input2_data,
-                                      const RuntimeShape &output_shape,
-                                      float *output_data)
+        inline void SetActivationMinMax(const ArithmeticParams &params,
+                                        float *activation_min, float *activation_max)
         {
+            *activation_min = params.float_activation_min;
+            *activation_max = params.float_activation_max;
+        }
+
+        inline void SetActivationMinMax(const ArithmeticParams &params,
+                                        int64_t *activation_min,
+                                        int64_t *activation_max)
+        {
+            *activation_min = params.int64_activation_min;
+            *activation_max = params.int64_activation_max;
+        }
+
+        template <typename T>
+        inline void SubWithActivation(
+            const ArithmeticParams &params, const RuntimeShape &input1_shape,
+            const T *input1_data, const RuntimeShape &input2_shape,
+            const T *input2_data, const RuntimeShape &output_shape, T *output_data)
+        {
+            ruy::profiler::ScopeLabel label("SubWithActivation");
             const int flat_size =
                 MatchingElementsSize(input1_shape, input2_shape, output_shape);
+            T activation_min, activation_max;
+            SetActivationMinMax(params, &activation_min, &activation_max);
+
             for (int i = 0; i < flat_size; ++i)
             {
                 output_data[i] = ActivationFunctionWithMinMax(
-                    input1_data[i] - input2_data[i], params.float_activation_min,
-                    params.float_activation_max);
+                    input1_data[i] - input2_data[i], activation_min, activation_max);
             }
         }
 

```
</details>

@tcal-x @alanvgreen Please take a look.

**Comment by tcal-x** [comment]
@alanvgreen , is this local version of `sub.h` in `mnv2_first` for a one-time experimental data collection, or is it required for correct functionality?   Robert made a clear diff above.

**Comment by alanvgreen** [comment]
Looking at git history, the meaningful change is: 
```
+#ifdef SHOW_ARITHMETIC_PARAMS
+            print_arithmetic_params("SUB", params, input1_shape, input2_shape, output_shape);
+#endif
```

There are similar changes for add.h, mul.h and depthwise_conv.h. 

I'll send a PR to remove all references to SHOW_ARITHMETIC_PARAMS, then these files can be removed too.

**Comment by alanvgreen** [comment]
https://github.com/google/CFU-Playground/pull/350

**Comment by tcal-x** [comment]
Hi @robertszczepanski , you'll need to resolve now that sub.h and similar files have been deleted.   Thanks!

**Comment by robertszczepanski** [comment]
Hi @tcal-x, I removed `sub.h`. TFLite Micro `micro_memory_planner` fix has been merged into upstream: https://github.com/tensorflow/tflite-micro/pull/698 so I removed a patch as well.

I think this PR is ready to be merged right now.

**Comment by alanvgreen** [comment]
LGTM. I'll let @tcal-x approve.

Thanks, Robert!

**Review by tcal-x — APPROVED** [review]
LGTM
Thanks @robertszczepanski !
I've tested every way I can think of, including on the proto2 board, and everything works fine.

**Pull request merged**
