### PR TITLE
Bump submodules incl. litex, litex-boards.

### PR DESCRIPTION
**Pull request by tcal-x**
Signed-off-by: Tim Callahan <tcal@google.com>

### CODE REVIEW

**Comment by JosephBushagour** [comment]
LGTM

**Review by JosephBushagour — APPROVED** [review]

**Comment by tcal-x** [comment]
This brings in a change from LiteX that Joey needs for other PRs: https://github.com/enjoy-digital/litex/commit/c79e428fe195f357a4bf616a643250904e848188

**Review by danc86 — APPROVED** [review]
I tested my WIP HPS accelerator project on Arty with these changes, looks fine to me

**Comment by tcal-x** [comment]
> I tested my WIP HPS accelerator project on Arty with these changes, looks fine to me

Thanks Dan!

**Pull request merged**
