### PR TITLE
Litespi perf submodules

### PR DESCRIPTION
**Pull request by pawelsag**
Changing submodules to the ones that allow test performance of the litespi.
During tests, some data has been captured. There was always 0x1000000 bytes read.
 
The measured data were:
 - number of cycles when CS was active during the whole transmission
 - the maximal throughput 

Sequential access with 25Mhz SCK. 

| SPI Varian | CS count    | Throughput  |
| ------------- | ------------- | -----:|
| READ_1_1_1 | 301994911  | 2.6MiB/s |
| READ_1_1_2 | 167775238    |  4.7MiB/s |
| READ_1_1_4 | 100666374    |  7.9MiB/s |

Random access with 25Mhz SCK.
The Random access can be considered when we read address no sequential eg. with step=2,3,4...
The step size doesn't matter if it comes to the performance.
The result below was calculated with step=2.

| SPI Varian | CS count   | Throughput  |
| ------------- | ------------- |-----:|
| READ_1_1_1 | 574624728    |  1.3MiB/s |
| READ_1_1_2 | 507516107    |  1.5MiB/s |
| READ_1_1_4 | 440407000    |  1.7MiB/s |

### CODE REVIEW

**Comment by tcal-x** [comment]
We'll need to consider how to handle the submodules, especially when there were already CFU-Playground-specific changes on another fork.   We could try to upstream generally useful improvements; we could move some of the benchmarking into CFU-Playground code; we could merge the submodule changes; or we could keep the litespi investigation code on a non-main CFU Playground branch.

**Comment by tmichalak** [comment]
@googlebot I fixed it.

**Comment by tcal-x** [comment]
This is the error seen with the checks: `litex.build.generic_platform.ConstraintError: Resource not found: serial:None`



```
Traceback (most recent call last):
  File "./common_soc.py", line 54, in <module>
    main()
  File "./common_soc.py", line 50, in main
    workflow.run()
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/general.py", line 111, in run
    soc = self.make_soc()
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/digilent_arty.py", line 27, in make_soc
    return super().make_soc(l2_size=8 * 1024, with_jtagbone = False, **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/general.py", line 74, in make_soc
    return self.soc_constructor(**base_soc_kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex_boards/litex_boards/targets/digilent_arty.py", line 115, in __init__
    serial = platform.request('serial')
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/generic_platform.py", line 314, in request
    return self.constraint_manager.request(*args, **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/generic_platform.py", line 194, in request
    resource = _lookup(self.available, name, number, loose)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/build/generic_platform.py", line 99, in _lookup
    raise ConstraintError("Resource not found: {}:{}".format(name, number))
litex.build.generic_platform.ConstraintError: Resource not found: serial:None
make[1]: Leaving directory '/home/runner/work/CFU-Playground/CFU-Playground/soc'
make[1]: *** [/home/runner/work/CFU-Playground/CFU-Playground/soc/common_soc.mk:96: build/digilent_arty.mnv2_first/software/bios/bios.bin] Error 1
make: *** [../proj.mk:243: litex-software] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by pawelsag** [comment]
Closing:
superseded by #149

**Pull request closed without merging**
