### PR TITLE
hps_accel: Support shifting right by 2

### PR DESCRIPTION
**Pull request by davidlattimore**
This is needed for a new model that we'll be using.

Signed-off-by: David Lattimore <dml@google.com>

### CODE REVIEW

**Review by danc86 — APPROVED** [review]
LGTM but it would be nice if we could also have a matching assertion on the C++ side, for the shift values we can handle here, to prevent this problem in future.

**Comment by davidlattimore** [comment]
Turns out we need to support shifting right by 12 as well, so I updated the commit to include that.

I also added a commit that checks if the shift is within the supported range.

**Review by danc86 — APPROVED** [review]
Very nice

**Pull request merged**
