### PR TITLE
Issue 582 workaround

### PR DESCRIPTION
**Pull request by davidlattimore**

### CODE REVIEW

**Comment by davidlattimore** [comment]
This is an optional workaround for #582. It's off by default since it does incur a small performance penalty.

**Review by danc86 — APPROVED** [review]
Making it conditional sounds good, we will want to define this for hps_accel in a followup commit I guess?

Let's see what tcal thinks about this approach of patching the SaxonSoc header though.

**Review by tcal-x — APPROVED** [review]
LGTM!

**Comment by davidlattimore** [comment]
We have now submitted a proper fix for this in hps-firmware and have rolled back the equivalent of this PR. I'll wait until we've updated VexRiscv in CFU Playground and confirmed that the bug no longer reproduces here. Then we can abandon this PR.

**Pull request merged**
