### PR TITLE
hps: remove monkey-patch for Oxide lack of I/O flip-flop

### PR DESCRIPTION
**Pull request by danc86**
It was fun while it lasted :monkey:

### CODE REVIEW

**Review by tcal-x — APPROVED** [review]
LGTM

**Comment by alanvgreen** [comment]
LGTM, too

**Comment by danc86** [comment]
Oh, but I forgot we still have a fork of Litex. This PR accidentally switches us back to the upstream Litex master branch, which breaks Fomu and Icebreaker (thank goodness for pre-merge CI):

```
ERROR:SoC:fomu+cfu CPU variant not supported, supporteds: minimal, minimal+debug, lite, lite+debug, standard, standard+debug, imac, imac+debug, full, full+cfu, full+debug, full+cfu+debug, linux, linux+debug, linux+no-dsp, secure, secure+debug.
Traceback (most recent call last):
  File "./common_soc.py", line 57, in <module>
    main()
  File "./common_soc.py", line 53, in main
    workflow.run()
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/general.py", line 113, in run
    soc = self.make_soc()
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/ice40up5k.py", line 59, in make_soc
    **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/soc/board_specific_workflows/general.py", line 76, in make_soc
    return self.soc_constructor(**base_soc_kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex_boards/litex_boards/targets/1bitsquared_icebreaker.py", line 88, in __init__
    **kwargs)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/soc/integration/soc_core.py", line 191, in __init__
    cfu           = cpu_cfu)
  File "/home/runner/work/CFU-Playground/CFU-Playground/third_party/python/litex/litex/soc/integration/soc.py", line 888, in add_cpu
    raise
RuntimeError: No active exception to reraise
```

**Comment by tcal-x** [comment]
> Oh, but I forgot we still have a fork of Litex. This PR accidentally switches us back to the upstream Litex master branch, which breaks Fomu and Icebreaker (thank goodness for pre-merge CI):

I've rebased the fomu changes on top of lastest upstream master.   So the fork/branch to use for the litex submodule is my fork (tcal-x), branch "fomu-cfu", and to check, you should get commit `b59ce45a`.

**Comment by danc86** [comment]
Thanks @tcal-x. I've amended this PR to use that commit for the Litex submodule. Let's see if the tests all pass now.

**Pull request merged**
