### PR TITLE
Add GCC dependency

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This is required to build flashrom.

### CODE REVIEW

**Review by tcal-x — COMMENTED** [review]
Hi @PiotrZierhoffer  -- what is this needed for?   It's to build something that runs on the host, right?

**Comment by PiotrZierhoffer** [comment]
The setup script builds flashrom, and it requires gcc to be installed.

**Comment by tcal-x** [comment]
> The setup script builds flashrom, and it requires gcc to be installed.

Ah now I see your earlier comment.

**Review by tcal-x — APPROVED** [review]
LGTM

**Pull request merged**
