### PR TITLE
Fix broken formatting that was hiding text in gateware.rst

### PR DESCRIPTION
**Pull request by marcmerlin**

### CODE REVIEW

**Comment by marcmerlin** [comment]
Side note, the instructions say
```
$ cd $HOME
$ virtualenv -p python3 nmigen-tutorial
$ cd ~/playground
$ git clone https://github.com/WRansohoff/nmigen_getting_started.git
```

how about using the same directory for both instead of completely different ones?

**Comment by mithro** [comment]
I would suggest that the flow should be;
```
$ git clone https://github.com/XXXX.git
$ cd XXXX
$ make env
$ ...
```

**Comment by mithro** [comment]
FYI - @marcmerlin - Don't forget to request a reviewer if you want someone to actually look at this.

**Comment by marcmerlin** [comment]
@mithro  ooh, I missed the reviewer feature, hadn't seen it before, thanks.
Yes, agreed on virtualenv, it was a bit confusing to use different directories in the tutorial

**Comment by marcmerlin** [comment]
@alanvgreen  since the PR with API fixes never got merged after over a year, how about telling people to clone the fixed version instead?
https://github.com/alanvgreen/nmigen_getting_started/tree/updated_api ?

**Comment by marcmerlin** [comment]
Let's table the discussion on fixing the instructions to the next PR which I can't start before this one goes in.
I'll submit a bunch of small fixes, including a fixed version of the code in the instructions in the other site.

**Review by alanvgreen — APPROVED** [review]
LGTM, thanks!

**Comment by marcmerlin** [comment]
@mithro  there may be an issue with the review/approve system.
@alanvgreen was suggested as a reviewer by github, he gave me approval, and I still cannot submit.
Are there ACL issues there, shouldn't Alan's approve allow me to submit?

**Comment by mithro** [comment]
@marcmerlin -- GitHub doesn't allow non-committers to submit, even if they have approval. I'll upgrade you to a committer.

**Comment by marcmerlin** [comment]
Thanks @mithro , let me know when I'm added and I'll try to commit this.

**Comment by mithro** [comment]
Should be working right now?

**Comment by marcmerlin** [comment]
sorry, not yet "You’re not authorized to merge this pull request."

**Pull request merged**
